### PR TITLE
Add AceJump to examples

### PR DESCRIPTION
**Pull request by breandan**

### CODE REVIEW

**Comment by zolotov** [comment]
Cool!

README.md is generated file by `documentr` task. Please change `src/docs/examples.md` instead. Also add a note that `kotlin` is used as a language for gradle-stript, it's quite unique at them moment and might be useful as an example

**Comment by zolotov** [comment]
Regeneration README.md is still needed, comment about kotlin-script is still needed. Also, please rebase the branch. I believe even 2 commit is too much for such change

**Comment by breandan** [comment]
Cool! I rebased the branch, merged the changes, updated `examples.md`, regenerated `examples.md` with `./gradlew documentr`, and re-submitted changes in a single commit. Just out of curiosity, how did you find the [documentr](https://github.com/synapticloop/documentr) plugin and what benefits does it provide?

**Comment by zolotov** [comment]
> Cool! I rebased the branch

Well, I see, but it is not what I wanted. I won't merge 40 commits for adding an example :)

> how did you find the documentr plugin and what benefits does it provide?

I didn't remember how I find it. The main reason to use it was updating plugin version across  documentation.

**Comment by breandan** [comment]
> I won't merge 40 commits for adding an example :)

The commits are already merged (those are mostly your commits). Or: I can close this one and resubmit another PR using the latest master branch.

**Comment by zolotov** [comment]
> The commits are already merged (those are mostly your commits)

No, they are not, they are different commits which were created during your rebase, and they will be duplicated in master as soon as I rebase master onto your branch.
Please follow the instruction on how to make PR rebasing: https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

> I can close this one and resubmit another PR using the latest master branch.

If you not sure how to handle this, probably it's easier to resubmit the PR.

**Comment by breandan** [comment]
> If you not sure how to handle this, probably it's easier to resubmit the PR.

Resubmitting under #181.

**Pull request closed without merging**
