### PR TITLE
Provide support for custom plugin repositories in official format #528

### PR DESCRIPTION
**Pull request by piotrtomiak**

### CODE REVIEW

**Comment by zolotov** [comment]
LGTM

**Comment by rachelcarmena** [comment]
Thank you so much @piotrtomiak :tada: :woman_dancing: 

Please @zolotov , is it available on `0.5.0-SNAPSHOT` after merging on `Jetbrains:master`? Thanks in advance!

**Comment by zolotov** [comment]
Not yet, if all tests will be passed it will take almost an hour until it gets into 0.5 snapshot. I'll ping you here as soon as it happens.

**Comment by rachelcarmena** [comment]
Awesome, thank you so much @zolotov :raised_hands:

**Comment by zolotov** [comment]
@rachelcarmena published. Please try now, probably `--refresh-dependencies` option will be required to upgrade snapshot.

**Comment by rachelcarmena** [comment]
Thanks @zolotov :raised_hands: It still doesn't work though I'll try it again later:

```
$ ls -ltr /home/rachel/.gradle/caches/modules-2/files-2.1/org.jetbrains.intellij.plugins/gradle-intellij-plugin/0.5.0-SNAPSHOT/1caef44e32a9596267368294c6acb67cf7d6feca/gradle-intellij-plugin-0.5.0-SNAPSHOT.jar 
-rw-r--r-- 1 rachel rachel 429040 oct  1 13:57 /home/rachel/.gradle/caches/modules-2/files-2.1/org.jetbrains.intellij.plugins/gradle-intellij-plugin/0.5.0-SNAPSHOT/1caef44e32a9596267368294c6acb67cf7d6feca/gradle-intellij-plugin-0.5.0-SNAPSHOT.jar

```
```
$ md5sum /home/rachel/.gradle/caches/modules-2/files-2.1/org.jetbrains.intellij.plugins/gradle-intellij-plugin/0.5.0-SNAPSHOT/1caef44e32a9596267368294c6acb67cf7d6feca/gradle-intellij-plugin-0.5.0-SNAPSHOT.jar
874d6d668e99785e3063aa49ee2e0ac9  /home/rachel/.gradle/caches/modules-2/files-2.1/org.jetbrains.intellij.plugins/gradle-intellij-plugin/0.5.0-SNAPSHOT/1caef44e32a9596267368294c6acb67cf7d6feca/gradle-intellij-plugin-0.5.0-SNAPSHOT.jar
```

Thanks again!!

**Comment by rachelcarmena** [comment]
@zolotov , @piotrtomiak it works like a charm :tada: :woman_dancing: I couldn't make it work with `0.5.0-SNAPSHOT`. I had to publish the plugin into my local repository from `master` branch to check it. 

Looking forward to the next release!!

Thank you sooo much!!!!! :raised_hands:

**Comment by rachelcarmena** [comment]
FYI: I cleaned my Gradle cache and I got a jar for `0.5.0-SNAPSHOT` with the same `MD5` as before (https://github.com/JetBrains/gradle-intellij-plugin/pull/540#issuecomment-702090665) in case it's useful for you to review it.

**Pull request merged**
