### PR TITLE
issue#173 runIdea set systemProperties

### PR DESCRIPTION
**Pull request by huoguangjin**
please check [issue#173 intellij.systemProperties does not work](https://github.com/JetBrains/gradle-intellij-plugin/issues/173)

thank you

### CODE REVIEW

**Comment by zolotov** [comment]
test is required

**Comment by zolotov** [comment]
ok, looks like it's not easy to test `runIdea` task and it works fine for `test` task

**Comment by huoguangjin** [comment]
I'm sorry to reply so late

I know little about groovy and spock, and keep learning these days
I try to write test for hours, and here are some ways to test `runIdea`:

1. add a test flag to `RunIdeaTask.groovy`, in `exec()` method, check the flag and skip calling `super.exec()`, at last check the setting of `runIdea`
2. mock(or hook) main class "com.intellij.idea.Main" and check the SystemProperties, is it possible?..
3. just add `runIdea.doLast { ... }` to `buildFile` and check the task info from `standardOutput`, this's not a good idea because there is no callback after idea set up..

Maybe the first one is the easiest, but it will make the source code a little bit unpretty😥...

If you have a better idea, please let me know
Thank you

**Comment by zolotov** [comment]
Thanks for the update. Indeed, the first option is the easiest to implement and to maintain. You may want to implement it in another PR, but to be honest I'm fine without this test.

**Comment by huoguangjin** [comment]
All right, thank you

**Pull request merged**
