### PR TITLE
intellij.publish  properties are deprecated

### PR DESCRIPTION
**Pull request by izhangzhihao**

### CODE REVIEW

**Comment by zolotov** [comment]
Thank you, this is good idea to update an example.

1. README.md is generated by `documentr` task
2. `publishPlugin` is not a property of `intellij` extension, it's a task and should be configured as a task.

**Comment by izhangzhihao** [comment]
@zolotov The file named "src/docs/build.gradle.md.templar" is been updated.

**Comment by zolotov** [comment]
@izhangzhihao it's still needed to run `./gradlew documentr` to regenerated README.md. The suggested

**Comment by izhangzhihao** [comment]
@zolotov README.md is up to date now. Thanks for your suggestions.

**Comment by zolotov** [comment]
Thanks!

**Pull request merged**
