### PR TITLE
Patch JbreArtifact for new jbr-11* style JBRE. Set the repo to new re…

### PR DESCRIPTION
**Pull request by vicky17d**
…po for all JBREs starting with jbr-*

### CODE REVIEW

**Comment by zolotov** [comment]
Why? Does any ide contain jbr-* version?

**Comment by vicky17d** [comment]
This will require the user to specify the new style jbr-* with the prefix 'jbr-'
Else it is hard to differentiate between jbsdk11, jbr-11.

**Comment by zolotov** [comment]
Why do you need to specify jbr-prefixed runtime? In readme said that only jbrx and jbsdk are supported.

Why do you need differentiate them? What’s your usecase?

**Comment by vicky17d** [comment]
Usecase: 
intellij {
    version 'IC-191.5701.16'
    runIde {
        jbreVersion '???'  //for jbr-11_0_2-osx-x64-b159.tar.gz
    }
}

**Comment by zolotov** [comment]
Good question. Maybe it shouldn’t be named like that. Let me figure out why it looks so and I’ll get back to the pr after

**Comment by zolotov** [comment]
>         jbreVersion '???'  //for jbr-11_0_2-osx-x64-b159.tar.gz

Could you try `jbreVersion '11_0_2b159'`?

**Comment by zolotov** [comment]
I believe suggested changes won't make jbr-11_0_2-osx-x64-b159 string work. Pushed other changes. Please try 0.5.0-SNAPSHOT. `jbr-11_0_2b159` or `11_0_2b159` should work there

**Comment by vicky17d** [comment]
ok.. Trying now..
so I infer that the following will not be supported

_**jbsdk11**_
jbsdk11b105_linux_x64.tar.gz
 
 
**_jbsdk8_**
jbsdk8u112b287.2_osx_x64.tar.gz
jbsdk8u152b1136.26_linux_x86.tar.gz
 
**_jbsdk9_**
jbsdk9b131_linux_x64.tar.gz
 
**_openjdk 1.8_**
openjdk.1.8.release.b162.tar.gz
 
**_openjdk 8_**
openjdk8.linux64.b18.tar.gz

**Comment by vicky17d** [comment]
Works.. Thanks

**Comment by vicky17d** [comment]
Just FYI..
The correct version of jbre is downloaded now but
the javaexec fails because of https://youtrack.jetbrains.com/issue/JBR-1251
so for now.. manually copying the contents of
`.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbr-11_0_2-osx-x64-b159/jdk/Contents/Home`
to 
`.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbr-11_0_2-osx-x64-b159/jdk/Contents/Home/jre`
to make it work

**Comment by zolotov** [comment]
thanks, fixed

**Pull request closed without merging**
