### PR TITLE
Remove redundant plugin application in plugins usage

### PR DESCRIPTION
**Pull request by JakeWharton**

### CODE REVIEW

**Comment by Turbo87** [comment]
@JakeWharton missed one: https://github.com/JetBrains/gradle-intellij-plugin/blob/c7a2a5cc81c17e7dd966077b96aa22be25efaf73/README.md#buildgradle :wink:

**Comment by JakeWharton** [comment]
Oops! I'm out, will update later. Good spot.

**Comment by zolotov** [comment]
@Turbo87 the second one is required, see https://plugins.gradle.org/plugin/org.jetbrains.intellij

**Comment by zolotov** [comment]
@JakeWharton thanks

**Comment by JakeWharton** [comment]
I would actually be supportive of eliminating all of the mechanism of adding the plugin from @Turbo87's linked code. That part of the README should only focus on usage, not how to apply the plugin.

**Comment by Turbo87** [comment]
I think you mean a different "second" one than I do. The one at the bottom is definitely not needed.

**Pull request merged**
