### PR TITLE
debugIdea task added

### PR DESCRIPTION
**Pull request by gmandnepr**
This pull request adds task to start idea with installed plugin in debug mode.

### CODE REVIEW

**Comment by zolotov** [comment]
Why do you need this?

**Comment by gmandnepr** [comment]
I was debugging idea to find what code is triggered by some of the actions.
Also it was useful to understand what data is stored in PSI tree. Sometimes it is easier to evaluate expression then trying to find it in PSI viewer.

**Comment by zolotov** [comment]
And what're you going to use for debug?

**Comment by gmandnepr** [comment]
Idea is used to debug other instance of idea started by the plugin.

**Comment by zolotov** [comment]
Won't merged then. IDEA is able debug gradle task without hardcoding debug port and introducing new task type.

screenshot 2016-01-13 17 18 00

**Pull request closed without merging**
