### PR TITLE
Fix example project's link

### PR DESCRIPTION
**Pull request by oldergod**
cc @AlecStrong

### CODE REVIEW

**Comment by JakeWharton** [comment]
Why don't we just link to the repo?

**Comment by AlecStrong** [comment]
i believe it was so that the linked directory had the gradle file which applied this plugin directly

**Comment by JakeWharton** [comment]
Yeah that makes sense. But it should be fairly easy to discover based on the folder name. Plus few others link to anything but the enclosing repo.

**Comment by zolotov** [comment]
README.md is generated. Could you please edit `src/docs/examples.md`, regenerate readme with `documentr` task and push both files? Thanks

**Comment by oldergod** [comment]
Done.

**Pull request merged**
